### ISSUE TITLE
df -l not universally supported

### ISSUE THREAD

**Issue by lrvick** [osiegmar/cloudwatch-mon-scripts-python#10]
'df -l' is not supported in busybox based df which makes it difficult to run this package as a part of a minimal docker container.

See: https://github.com/osiegmar/cloudwatch-mon-scripts-python/blob/master/cloudwatchmon/cli/put_instance_stats.py#L368

**Comment by osiegmar** [comment]
I assume that the -l is not really required. Can you please try it without the -l and give me feedback if it works?

**Comment by lrvick** [comment]
Works fine for me without it.
