### ISSUE TITLE
3.x >= 2.6, yet this doesn't support Python 3.

### ISSUE THREAD

**Issue by ztane** [osiegmar/cloudwatch-mon-scripts-python#12]
As the title said, please add trove classifier Python 2 only, or preferably fix for Python 3 / polyglot.

**Comment by osiegmar** [comment]
Thanks for bringing this up! Unfortunately I currently have no time for adding Python 3 compatibility. So, I added Python 2 only trove categorization for now...

**Comment by osiegmar** [comment]
Python 3 is now supported
