### ISSUE TITLE
error while run example

### ISSUE THREAD

**Issue by Sanyorke-Han** [osiegmar/cloudwatch-mon-scripts-python#17]
use python 3.4 under CentOS 7.3, IAM role setting properly, encounter error while run for example:
[xxxxx ~]$ mon-put-instance-stats.py --mem-util --disk-space-util --disk-path=/
ERROR: Unicode-objects must be encoded before hashing

**Comment by osiegmar** [comment]
Python 3 is currently not supported - See #12.

**Comment by osiegmar** [comment]
This is now fixed in 2.0.6
